source 'https://rubygems.org'

gem 'cowsay'
gem 'devise' 
gem 'rails', '4.1.1'
gem 'sqlite3', '>= 1.3.10', :group => :development
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'annotate', github: 'ctran/annotate_models'
gem 'rack-cors', require: "rack/cors"

group :production do
  gem 'pg', '0.12.2'
end
